// Generated by Zite. Do not edit.
declare namespace NodeJS {
  interface ProcessEnv {
    /** Public URL of the current app. */
    ZITE_APP_URL: string;
    /** googlesheets access token (googlesheets-aspire-survey) */
    ZITE_GOOGLESHEETS_ACCESS_TOKEN: string;
    [key: string]: string | undefined;
  }
}

