-- Starter Question Library: a shared set of ready-to-use questions covering every
-- question type the engine supports, so a new workspace is not an empty page.
-- Idempotent: a question is inserted only if no shared question with the same
-- definition id and category already exists, so re-running never duplicates.
-- Real product content (organization_id null = shared with every workspace).
insert into public.question_library (organization_id, definition, category, tags, language, help_text, is_active, created_by)
select v.organization_id, v.definition, v.category, v.tags, v.language, v.help_text, true, v.created_by
from (values
  (null::uuid, '{"id":"enps","type":"nps","label":"On a scale of 0 to 10, how likely are you to recommend working here to a friend?","required":true,"lowLabel":"Not at all likely","highLabel":"Extremely likely"}'::jsonb, 'Engagement', array['nps', 'promoter']::text[], 'en', 'Employee Net Promoter Score. 9-10 promoters, 7-8 passives, 0-6 detractors.', 'Aspire starter library'),
  (null::uuid, '{"id":"overall_satisfaction","type":"rating","label":"Overall, how satisfied are you with your job?","required":true,"max":5,"shape":"star"}'::jsonb, 'Engagement', array['rating']::text[], 'en', 'A five-star overall satisfaction rating.', 'Aspire starter library'),
  (null::uuid, '{"id":"engagement_items","type":"matrix","label":"How much do you agree with each statement?","required":true,"rows":["I am proud to work here","I understand how my work contributes to our goals","I would still be here in a year","I have the tools I need to do my job well"],"scale":["Strongly disagree","Disagree","Neutral","Agree","Strongly agree"],"columnPrefix":"engagement_items"}'::jsonb, 'Engagement', array['likert', 'matrix']::text[], 'en', 'Four core engagement statements on an agreement scale.', 'Aspire starter library'),
  (null::uuid, '{"id":"considering_leaving","type":"yesno","label":"Have you thought about leaving in the last three months?","required":true}'::jsonb, 'Engagement', array['retention', 'yes-no']::text[], 'en', 'A direct retention-risk question.', 'Aspire starter library'),
  (null::uuid, '{"id":"leave_reasons","type":"checkbox","label":"What are the main reasons?","required":false,"options":["Pay","Career growth","My manager","Workload","Culture","Location or flexibility","Other"],"maxSelections":3,"randomize":true}'::jsonb, 'Engagement', array['retention', 'follow-up']::text[], 'en', 'Follow-up to the retention-risk question. After adding it, set it to show only when that answer is Yes.', 'Aspire starter library'),
  (null::uuid, '{"id":"workload","type":"slider","label":"How full is your workload right now?","required":false,"min":0,"max":100,"step":5,"unit":"%","lowLabel":"Far too light","highLabel":"Overwhelming"}'::jsonb, 'Engagement', array['workload', 'slider']::text[], 'en', 'A slider from an empty plate to an overwhelming one.', 'Aspire starter library'),
  (null::uuid, '{"id":"manager_support","type":"rating","label":"How supported do you feel by your manager?","required":true,"max":5,"shape":"star"}'::jsonb, 'Manager Effectiveness', array['rating']::text[], 'en', 'Star rating of manager support.', 'Aspire starter library'),
  (null::uuid, '{"id":"manager_behaviours","type":"matrix","label":"My manager...","required":true,"rows":["gives me clear expectations","gives me useful feedback","recognises good work","supports my development"],"scale":["Never","Rarely","Sometimes","Often","Always"],"columnPrefix":"manager_behaviours"}'::jsonb, 'Manager Effectiveness', array['likert', 'matrix']::text[], 'en', 'Four observable manager behaviours on a frequency scale.', 'Aspire starter library'),
  (null::uuid, '{"id":"manager_one_change","type":"textarea","label":"What is one thing your manager could do differently to help you?","required":false,"maxLength":600}'::jsonb, 'Manager Effectiveness', array['open-text']::text[], 'en', 'Open-ended manager feedback, capped at 600 characters.', 'Aspire starter library'),
  (null::uuid, '{"id":"enablers","type":"ranking","label":"Rank these from most to least important for doing your best work.","required":true,"options":["Clear goals","Regular feedback","The right tools","Time to focus","Learning opportunities"],"randomize":true}'::jsonb, 'Performance', array['ranking']::text[], 'en', 'Forces a trade-off between enablers.', 'Aspire starter library'),
  (null::uuid, '{"id":"goal_clarity","type":"radio","label":"How clear are your goals for this quarter?","required":true,"options":["Very clear","Mostly clear","Somewhat unclear","Not clear at all"]}'::jsonb, 'Performance', array['radio']::text[], 'en', 'Single-choice clarity check.', 'Aspire starter library'),
  (null::uuid, '{"id":"training_usefulness","type":"rating","label":"How useful was the training for your day-to-day work?","required":true,"max":5,"shape":"number","lowLabel":"Not useful","highLabel":"Very useful"}'::jsonb, 'Training', array['rating']::text[], 'en', 'Numbered 1-5 usefulness rating.', 'Aspire starter library'),
  (null::uuid, '{"id":"applied_learning","type":"yesno","label":"Have you applied what you learned in the last 30 days?","required":true}'::jsonb, 'Training', array['yes-no']::text[], 'en', 'Application check, a Level 3 (behaviour) indicator.', 'Aspire starter library'),
  (null::uuid, '{"id":"blockers","type":"textarea","label":"What has stopped you applying it?","required":false}'::jsonb, 'Training', array['follow-up', 'open-text']::text[], 'en', 'Follow-up for people who have not applied the learning. After adding it, set it to show only when the application question is No.', 'Aspire starter library'),
  (null::uuid, '{"id":"hours_spent","type":"number","label":"Roughly how many hours did you spend on the programme?","required":false,"min":0,"max":200,"unit":"hours"}'::jsonb, 'Training', array['number']::text[], 'en', 'A bounded number with a unit.', 'Aspire starter library'),
  (null::uuid, '{"id":"habit_frequency","type":"radio","label":"In the last two weeks, how often did you practise the new habit?","required":true,"options":["Every day","Most days","A few times","Once","Not at all"]}'::jsonb, 'Habit Formation', array['frequency', 'radio']::text[], 'en', 'Practice frequency.', 'Aspire starter library'),
  (null::uuid, '{"id":"habit_confidence","type":"slider","label":"How confident are you that you will keep it up?","required":true,"min":0,"max":10,"step":1,"lowLabel":"Not confident","highLabel":"Certain"}'::jsonb, 'Habit Formation', array['confidence', 'slider']::text[], 'en', '0-10 confidence slider.', 'Aspire starter library'),
  (null::uuid, '{"id":"behaviour_observed","type":"matrix","label":"Since the programme, how often have you seen the following?","required":true,"rows":["Colleagues using the new approach","Managers reinforcing it","It being used in meetings"],"scale":["Never","Rarely","Sometimes","Often","Always"],"columnPrefix":"behaviour_observed"}'::jsonb, 'Behaviour Change', array['likert', 'matrix']::text[], 'en', 'Observed behaviour change on a frequency scale.', 'Aspire starter library'),
  (null::uuid, '{"id":"belonging","type":"radio","label":"I feel I belong at this organisation.","required":true,"options":["Strongly agree","Agree","Neutral","Disagree","Strongly disagree"]}'::jsonb, 'Workplace Culture', array['radio', 'inclusion']::text[], 'en', 'A single belonging item.', 'Aspire starter library'),
  (null::uuid, '{"id":"culture_strengths","type":"checkbox","label":"Which of these describe our culture at its best? Choose up to three.","required":false,"options":["Collaborative","Innovative","Respectful","Fast-moving","Supportive","Accountable","None of the above"],"maxSelections":3,"randomize":true}'::jsonb, 'Workplace Culture', array['checkbox']::text[], 'en', 'Positive culture descriptors; "None of the above" stays last when randomised.', 'Aspire starter library'),
  (null::uuid, '{"id":"start_date","type":"date","label":"When did you join?","required":false,"max":"2030-12-31"}'::jsonb, 'Workplace Culture', array['date', 'onboarding']::text[], 'en', 'A calendar date.', 'Aspire starter library'),
  (null::uuid, '{"id":"customer_nps","type":"nps","label":"How likely are you to recommend us to a friend or colleague?","required":true,"lowLabel":"Not at all likely","highLabel":"Extremely likely"}'::jsonb, 'Customer Experience', array['nps', 'promoter']::text[], 'en', 'The classic customer Net Promoter Score question.', 'Aspire starter library'),
  (null::uuid, '{"id":"csat","type":"rating","label":"How satisfied were you with your experience today?","required":true,"max":5,"shape":"star"}'::jsonb, 'Customer Experience', array['rating', 'csat']::text[], 'en', 'CSAT on a five-star scale.', 'Aspire starter library'),
  (null::uuid, '{"id":"effort","type":"rating","label":"How easy was it to get what you needed?","required":true,"max":7,"shape":"number","lowLabel":"Very difficult","highLabel":"Very easy"}'::jsonb, 'Customer Experience', array['rating', 'ces']::text[], 'en', 'Customer Effort Score, 1-7.', 'Aspire starter library'),
  (null::uuid, '{"id":"priorities","type":"ranking","label":"Rank what we should improve first.","required":false,"options":["Speed","Price","Quality","Support","Range"],"randomize":true}'::jsonb, 'Customer Experience', array['ranking']::text[], 'en', 'Improvement priorities.', 'Aspire starter library'),
  (null::uuid, '{"id":"anything_else","type":"textarea","label":"Is there anything else you would like to tell us?","required":false,"maxLength":1000}'::jsonb, 'Customer Experience', array['open-text']::text[], 'en', 'A closing open-text question.', 'Aspire starter library'),
  (null::uuid, '{"id":"contact_email","type":"email","label":"If you would like us to follow up, leave your email address.","required":false,"placeholder":"name@company.com"}'::jsonb, 'Other', array['contact', 'identifier']::text[], 'en', 'Collects an email address. It identifies a person, so use it only in surveys that are not anonymous.', 'Aspire starter library'),
  (null::uuid, '{"id":"department","type":"select","label":"Which team are you in?","required":false,"options":["Operations","Sales","Engineering","People","Finance","Other"],"placeholder":"Choose your team"}'::jsonb, 'Other', array['select']::text[], 'en', 'A dropdown of teams. Edit the options to fit the customer.', 'Aspire starter library')
) as v(organization_id, definition, category, tags, language, help_text, created_by)
where not exists (
  select 1 from public.question_library l
  where l.organization_id is null and l.category = v.category
    and l.definition ->> 'id' = v.definition ->> 'id'
);
